### ISSUE TITLE
Error with Django 3.x

### ISSUE THREAD

**Issue by hawthorne-stephen-kelley** [staticdev/django-sorting-bootstrap#11]
File "/opt/hml/hmlvenv/lib/python3.7/site-packages/sorting_bootstrap/templatetags/sorting_tags.py", line 10, in <module>
    from sorting_bootstrap.util import label_for_field
  File "/opt/hml/hmlvenv/lib/python3.7/site-packages/sorting_bootstrap/util.py", line 7, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/opt/hml/hmlvenv/lib/python3.7/site-packages/django/utils/__init__.py)

Importing six directly rather than from django.utils seems to fix the error.

**Comment by staticdev** [comment]
@hawthorne-stephen-kelley I a bunch of fixes to make it usable on newer django. I commited on master before releasing a version. Can you test it please?

**Comment by hawthorne-stephen-kelley** [comment]
(hmlvenv) root@ip-10-0-1-184:/opt/hml/src# pip install --force-reinstall git+https://github.com/staticdev/django-sorting-bootstrap
Collecting git+https://github.com/staticdev/django-sorting-bootstrap
  Cloning https://github.com/staticdev/django-sorting-bootstrap to /tmp/pip-req-build-lpfj0ozc
  Running command git clone -q https://github.com/staticdev/django-sorting-bootstrap /tmp/pip-req-build-lpfj0ozc
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/hml/hmlvenv/bin/python3.7 /opt/hml/hmlvenv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpvk4exov0
         cwd: /tmp/pip-req-build-lpfj0ozc
    Complete output (20 lines):
    Traceback (most recent call last):
      File "/opt/hml/hmlvenv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/opt/hml/hmlvenv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/opt/hml/hmlvenv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-nap16m5j/overlay/lib/python3.7/site-packages/poetry/masonry/api.py", line 39, in prepare_metadata_for_build_wheel
        builder = WheelBuilder(poetry, SystemEnv(Path(sys.prefix)), NullIO())
      File "/tmp/pip-build-env-nap16m5j/overlay/lib/python3.7/site-packages/poetry/masonry/builders/wheel.py", line 44, in __init__
        super(WheelBuilder, self).__init__(poetry, env, io)
      File "/tmp/pip-build-env-nap16m5j/overlay/lib/python3.7/site-packages/poetry/masonry/builders/builder.py", line 69, in __init__
        includes=self._package.include,
      File "/tmp/pip-build-env-nap16m5j/overlay/lib/python3.7/site-packages/poetry/masonry/utils/module.py", line 72, in __init__
        source=package.get("from"),
      File "/tmp/pip-build-env-nap16m5j/overlay/lib/python3.7/site-packages/poetry/masonry/utils/package_include.py", line 15, in __init__
        self.check_elements()
      File "/tmp/pip-build-env-nap16m5j/overlay/lib/python3.7/site-packages/poetry/masonry/utils/package_include.py", line 37, in check_elements
        root = self._elements[0]
    IndexError: list index out of range
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/hml/hmlvenv/bin/python3.7 /opt/hml/hmlvenv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpvk4exov0 Check the logs for full command output.

Dr. Stephen Kelley
Principal Scientist

Work:     641.954.3383
Web:      hawthorneadvertising.com<http://www.hawthorneadvertising.com/>

[cid:image003.png@01D5F623.06007840]

Hawthorne Direct is now Hawthorne Advertising! Find us at www.hawthorneadvertising.com<http://www.hawthorneadvertising.com/>

This email message and any attached files are confidential and are intended solely for the use of the recipient(s) named above. If you are not the intended recipient or person responsible for delivering this confidential communication to the intended recipient, you have received this communication in error, and any review, dissemination, distribution or copying is strictly prohibited. If you have received this confidential communication in error, please notify the sender immediately by return email and permanently delete the original message (and any attachments) without reading or saving in any manner.

**Comment by staticdev** [comment]
@hawthorne-stephen-kelley I am sorry, I found a problem with pyproject.toml. Can you try again?

**Comment by staticdev** [comment]
@hawthorne-stephen-kelley I also made fixes and optimizations to make it cleaner when using Django 2.0+.

**Comment by virtustate** [comment]
Sorry. Got laid off and no access to work account. Is there another way to install this? Note below, there is no setup.py file in the temporary build directory that pip creates when I try to install from the git source.

(venv) ae@fluff:/tmp$ pip install --force-reinstall git+https://github.com/staticdev/django-sorting-bootstrap
Collecting git+https://github.com/staticdev/django-sorting-bootstrap
  Cloning https://github.com/staticdev/django-sorting-bootstrap to ./pip-ue2iuslj-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-ue2iuslj-build/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-ue2iuslj-build/
(venv) ae@fluff:/tmp$ cd pip-ue*
(venv) ae@fluff:/tmp/pip-ue2iuslj-build$ ls
CHANGES.md  MANIFEST.in  pip-delete-this-directory.txt  poetry.lock     README.md  src
LICENSE     noxfile.py   pip-egg-info                   pyproject.toml  sample

**Comment by staticdev** [comment]
@virtustate since PEP 517/518 there is no need for a setup.py, it is substituted by pyproject.toml. Iso your pip up to date? Can you try `pip install -U pip`?

**Comment by virtustate** [comment]
Thanks, that was it: old pip version. Installed and it works in my Django 3.0.4 project after changing the model name in INSTALLED_APPS from sorting_bootstrap to django_sorting_bootstrap.

**Comment by virtustate** [comment]
The install downgraded Django to 2.2.11, I'm guessing in running tests. Easy to re-install the new version. So the install from master worked in my application with Django 2.2.11 and 3.0.4. I assume when it's released, the install won't do all the Django version installs/uninstalls.

**Comment by staticdev** [comment]
@virtustate Please try to install version 2.0.0 released on PyPI.

**Comment by staticdev** [comment]
@virtustate I am so sorry, there was indeed an error on maximum allowed version for it. Please install version 2.0.1 with the bug fix!

**Comment by virtustate** [comment]
Thanks, works as expected in my Django 3.0.5 project.

**Comment by staticdev** [comment]
Nice @virtustate, I am looking for maintainers for this app. Are you interested?
Please give this repo a star if you are using it, for me to keep track of the priorities in all my apps.
