### ISSUE TITLE
Not able to install django-sorting-bootstrap

### ISSUE THREAD

**Issue by royki** [staticdev/django-sorting-bootstrap#306]
- OS: Ubuntu
- Python: v3.6.9 (virtualenv)

Issue:
- Not able to install `django-sorting-bootstrap`
- I tried multiple way to install it. But it failed. 

![image](https://user-images.githubusercontent.com/1545990/122643747-e0236f80-d111-11eb-96c7-bde775c9a904.png)

![2021-06-19_15h17_38](https://user-images.githubusercontent.com/1545990/122643715-b1a59480-d111-11eb-85ba-45bbed3bc2f0.jpg)

![2021-06-19_15h17_48](https://user-images.githubusercontent.com/1545990/122643718-b407ee80-d111-11eb-9072-eb5f9e75f7ae.jpg)

**Comment by rmassoth** [comment]
I believe this is because django-sorting-bootstrap only supports python 3.7+ but you are using 3.6.9. If you are able to upgrade your python version then you can install it using pip.

**Comment by staticdev** [comment]
@royki I would try upgrading python to 3.7 if possible and using latest version (today v2.7.0).

**Comment by staticdev** [comment]
@royki any luck?

**Comment by royki** [comment]
> @royki any luck?
Nope, not using for the moment. Using [Data Tables](https://datatables.net/) for the moment.

**Comment by staticdev** [comment]
Did you try with Python 3.7?
